/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/golfStats` | `/profile/golfStats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/start_round/activeRound` | `/start_round/activeRound`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/start_round/addCourse` | `/start_round/addCourse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/start_round/startRound` | `/start_round/startRound`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/golfStats` | `/profile/golfStats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/start_round/activeRound` | `/start_round/activeRound`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/start_round/addCourse` | `/start_round/addCourse`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/start_round/startRound` | `/start_round/startRound`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/golfStats${`?${string}` | `#${string}` | ''}` | `/profile/golfStats${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/start_round/activeRound${`?${string}` | `#${string}` | ''}` | `/start_round/activeRound${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/start_round/addCourse${`?${string}` | `#${string}` | ''}` | `/start_round/addCourse${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/start_round/startRound${`?${string}` | `#${string}` | ''}` | `/start_round/startRound${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/golfStats` | `/profile/golfStats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/start_round/activeRound` | `/start_round/activeRound`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/start_round/addCourse` | `/start_round/addCourse`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/start_round/startRound` | `/start_round/startRound`; params?: Router.UnknownInputParams; };
    }
  }
}
